import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

    const user = useUser()

    return (
        <>
            <Head>
                <title>Meu aplicativo</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div>
                    { user.isSignedIn? <p>Hello, User</p>: <p>Sign in to continue</p> }
                    { user.isSignedIn? <SignOutButton/>: <SignInButton/> }
                </div>
            </main>
        </>
    );
};

export default Home;
