import Head from 'next/head'
import { useState } from 'react'
import { CreatePostWizard } from '~/components/CreatePostWizard'
import { DataStateContext } from '~/components/DataStateContext'
import { Posts } from '~/components/Posts'
import type { UserData } from '~/utils/UserData'

export function Timeline({ data }: { data: UserData[] }): JSX.Element {
    // Hooks
    const [dataState, setDataState] = useState(data)

    return (
        <>
            <Head>
                <title>Meu aplicativo</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="mx-auto flex justify-center">
                <DataStateContext.Provider value={{ dataState, setDataState }}>
                    <div className="h-full w-full border-slate-400 md:max-w-4xl">
                        <div className="mb-2 w-full p-4">
                            <CreatePostWizard />
                        </div>
                        <Posts />
                    </div>
                </DataStateContext.Provider>
            </main>
        </>
    )
}
